# Generated by Django 5.0.4 on 2025-02-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edad', models.DecimalField(decimal_places=0, max_digits=3)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
